version: '3.8'

services:
  backend:
    build: ./server
    container_name: botica_backend
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - botica-network

  frontend:
    build: ./client
    container_name: botica_frontend
    ports:
      - "3000:80"
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - botica-network

networks:
  botica-network:
    driver: bridge
